### ISSUE TITLE
Bug in roundabout/__init__.py 

### ISSUE THREAD

**Issue by larsbutler** [ChristopherMacGown/roundabout#22]
If an exception occurs on roudabout/**init**.py, line 41, this happens:

Traceback (most recent call last):
  File "bin/roundabout", line 5, in <module>
    Roundabout.run()
  File "/home/larsbutler/roundabout/roundabout/**init**.py", line 43, in run
    except git.exc.GitCommandError:
AttributeError: 'Git' object has no attribute 'exc'

As a workaround, I just catch an Exception here.

**Comment by ChristopherMacGown** [comment]
Fixed in https://github.com/ChristopherMacGown/roundabout/commit/2196ba47b32a8d0a8144e9a49d7d65da7a64ff3c
